# Generated by Django 4.2.11 on 2024-08-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="discounts", to="api.category"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="is_auto_apply",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discount",
            name="is_percentage",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="discounts", to="api.product"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, related_name="discounts", to="api.subcategory"
            ),
        ),
    ]
