# Generated by Django 4.2.11 on 2024-12-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_discount_categories_discount_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_bestselling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
