# Generated by Django 5.1.4 on 2025-02-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_product_is_bestselling_product_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_bestselling",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
        migrations.AddField(
            model_name="category",
            name="cover",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
