# Generated by Django 5.1.4 on 2025-02-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_product_is_bestselling_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
