# Generated by Django 5.1.4 on 2025-02-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_category_description_alter_category_cover_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
