# Generated by Django 5.1.4 on 2025-02-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="feature_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
