# Generated by Django 5.1.6 on 2025-02-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_category_feature_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
