# Generated by Django 6.0.3 on 2026-05-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_category_name_alter_category_priority'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Expense',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('category', models.CharField(
                            choices=[
                                ('raw_materials', 'Raw Materials'),
                                ('chef_salary', "Chef's Salary"),
                                ('ads', 'Ad Spend'),
                                ('miscellaneous', 'Miscellaneous')
                            ],
                            max_length=50
                        )),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('description', models.CharField(blank=True, default='', max_length=255)),
                        ('date', models.DateField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                ),
            ],
            database_operations=[],
        ),

        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),

        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]